# Generated by Django 4.2.6 on 2023-12-11 00:51

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import product.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_type', models.CharField(
                    choices=[('POLL', 'Umfrage'), ('DATE', 'Terminabstimmung'), ('TIER', 'Tierlist'),
                             ('RANK', 'Rangliste')], max_length=4)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(default=product.models.generate_unique_code, editable=False, max_length=5)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('password', models.CharField(blank=True, max_length=50)),
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
                ('timestamp_end', models.DateTimeField(blank=True, null=True)),
                ('timestamp_changed', models.DateTimeField(auto_now=True)),
                ('show_result', models.BooleanField(default=False)),
                ('logged_in_only', models.BooleanField(default=False)),
                ('multiple_choice_allowed', models.BooleanField(default=False)),
                ('custom_answers_allowed', models.BooleanField(default=False)),
                ('date_mode', models.CharField(blank=True, choices=[('DATE', 'Datum'), ('TIME', 'Uhrzeit'),
                                                                    ('BOTH', 'Datum & Uhrzeit')], max_length=4,
                                               null=True)),
                ('num_tiers', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('criteria_good', models.CharField(blank=True, max_length=50, null=True)),
                ('criteria_bad', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                 to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VotingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=product.models.option_directory_path)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voting_options',
                                           to='product.poll')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes',
                                           to='product.poll')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                           related_name='votes', to='product.user')),
            ],
        ),
        migrations.CreateModel(
            name='PollView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.poll')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.user')),
            ],
        ),
        migrations.AddField(
            model_name='poll',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls_created',
                                    to='product.user'),
        ),
        migrations.AddField(
            model_name='poll',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='polls_participated', to='product.user'),
        ),
        migrations.AddField(
            model_name='poll',
            name='viewers',
            field=models.ManyToManyField(blank=True, related_name='polls_viewed', through='product.PollView',
                                         to='product.user'),
        ),
    ]
