# Generated by Django 4.2.6 on 2023-12-05 23:42

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankingobject',
            name='image',
            field=models.ImageField(default='null', upload_to=product.models.object_directory_path),
            preserve_default=False,
        ),
    ]
