# Generated by Django 4.2.6 on 2023-12-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rankingobject_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='choicepoll',
            name='viewers',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)ss_viewed', to='product.user'),
        ),
        migrations.AddField(
            model_name='datetimepoll',
            name='viewers',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)ss_viewed', to='product.user'),
        ),
        migrations.AddField(
            model_name='rankingpoll',
            name='viewers',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)ss_viewed', to='product.user'),
        ),
        migrations.AddField(
            model_name='tierlistpoll',
            name='viewers',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)ss_viewed', to='product.user'),
        ),
    ]
