# Generated by Django 4.2.6 on 2023-11-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_user_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='choicepoll',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='datetimepoll',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='rankingpoll',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tierlistpoll',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
