# Generated by Django 4.2.6 on 2023-12-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_choicepoll_viewers_datetimepoll_viewers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choicepoll',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='datetimepoll',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='rankingpoll',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='tierlistpoll',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
